---
title: "Code of Academic Conduct"
output: 
  html_document:
    theme: yeti
    toc: true
    toc_depth: 4
    toc_float: true
---

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-16099315-7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-16099315-7');
</script>

<br>

You should familiarize yourself with the UC Davis standards of academic conduct, available [here](https://supportjudicialaffairs.sf.ucdavis.edu/code-academic-conduct).
<br>
<br>

##### *Ensuring Equitable Access to Learning*

UC Davis is committed to educational equity in the academic setting, and in serving a diverse student body. I encourage all students who are interested in learning more about the Student Disability Center (SDC) to contact them directly at sdc.ucdavis.edu or 530-752-3184. If you are a student who currently receives academic accommodation(s), please submit your SDC Letter of Accommodation to me as soon as possible, ideally within the first two weeks of this course

##### *Cheating*
In this class, we will be doing a combination of group and individual assignments. The very ethos of this class is to build a collaborative network amongst the students, but also to support your individual development as scientists. Thus, I ask that you work together and lift each other up, but please not cheat or plagiarize (more information on plagiarism below) in this class.  If any part of your feels compelled to cheat to achieve the ‘Pass’ grade that this course requires, please come talk to me so we can develop a strategy for ensuring tat you succeed in this course.

Cheating will not be tolerated and anyone caught cheating will be reported to the Student Judicial Affairs Office. And, if you cheat, you will also make me very, very grumpy that I have to deal with this / you. Please don’t make me grumpy.

##### *Plagiarism*
Plagiarism is a form of cheating or fraud.  It occurs when a student misrepresents the work of another as his/her/their own. Plagiarism may consist of using ideas, sentences, paragraphs, or whole text of another without appropriate acknowledgment, and includes employing/allowing others to write/substantially alter work then submitted as his/her/their own. Placing copied text in quotes is unacceptable and constitutes plagiarism. If students provide the same answers for Problem Sets, this will constitute plagiarism for both students. Plagiarism will result in notification to the Department of Animal Science and the Student Judicial Affairs Office.

<center> **TL;DNR: Don’t Cheat. Don’t Plagiarize.** </center>
