---
output: 
  html_document:
    theme: yeti
---
<br>


# **Fall 2020: Professional Development Seminar**

### *More information coming soon!*

## Syllabus
* PDF coming soon

## Course Description
* This course is intended to help sophomore, junior and first-year transfer students in the MCS major build skills that will help them succeed in their undergraduate careers and beyond.

## Course Objectives
* X
* Y
* Z

## Course Schedule
* Week 1
* Week 2
* Week 3
* Week 4
* Week 5
* Week 6
* Week 7
* Week 8
* Week 9
* Week 10

## Code of Conduct
* coming soon
* See UC Davis [Principles of Community](https://diversity.ucdavis.edu/principles-community)

## Territorial Acknowledgement
We [acknowledge](https://native-land.ca/territory-acknowledgement/) that UC Davis campus exists on land that the Patwin/Suisune People have thrived on since time immemorial. As settlers, we must recognize how we benefit from colonialism and how it is has impacted the Native Peoples whose lands we now use. It is incumbent upon us to dismantle components of colonialism to ensure a more just and equitable future for the Patwin/Suisune People.

This acknowledgement was made possible by [native-land.ca](native-land.ca). Consider using this resource to determine which Native Peoples' lands you currently occupies.
